name: Unit Tests & Code Coverage

on: [push]

jobs:
  unit-tests:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:

      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run unit tests
        run: poetry run coverage run -m pytest tests/

      - name: Generate coverage xml report
        run: poetry run coverage xml

      - name: Submit Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true